### ISSUE TITLE
Generating Sound Hangs

### ISSUE THREAD

**Issue by Armandeus66** [acd-jake/acd-talking-actors#52]
Thanks for making this module!

Generating a sound hangs at "Working" and there is no new sound created. 

(I am subscribed to Elevenlabs.)

**Comment by acd-jake** [comment]
Hi, sorry for the late reply.

I just tested it and was able to generate sounds without any problems.

Is it still not working for you, or does the problem no longer exist?

**Comment by Armandeus66** [comment]
I tried it again and it hangs like I explained.

**Comment by acd-jake** [comment]
Can you check the debugging console of your browser? Does it show error messages when you try to generate sounds?

**Comment by Armandeus66** [comment]
Here is the error that pops up when I click on generate. (`Prompt: "A dog barking.")

GenerateSoundEffectsApp.js:90 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'replace')
[Detected 1 package: acd-talking-actors(0.8.1)]
    at GenerateSoundEffectsApp.convertToValidFilename (GenerateSoundEffectsApp.js:90:23)
    at GenerateSoundEffectsApp.generateEffectInternal (GenerateSoundEffectsApp.js:98:44)
    at async GenerateSoundEffectsApp.generateEffect (GenerateSoundEffectsApp.js:130:9)
convertToValidFilename	@	GenerateSoundEffectsApp.js:90
generateEffectInternal	@	GenerateSoundEffectsApp.js:98
await in generateEffectInternal		
generateEffect	@	GenerateSoundEffectsApp.js:130
dispatch	@	jquery.min.js:2
v.handle	@	jquery.min.js:2

**Comment by acd-jake** [comment]
Thank you for the information. Is it possible that you didn't enter a name for the sound effect? The filename under which the sound effect is saved is generated from this name. 

I will tighten up the input validation at this point again.

I would ask you, however, to try again with a different name – not prompt – for the sound effect. This way I can ensure that this was really your problem.

**Comment by Armandeus66** [comment]
Yes, that was the problem. Thanks.
The filename field is the same color as the dialog, and I didn't notice it. Sorry. Maybe it could be the color of the prompt window, or there could be a warning - "input a file name" for dummies like me.
Anyway, thank you!

**Comment by acd-jake** [comment]
There is now a completely reimplemented version of the module. Please check whether the issue still occurs with the current version.
If this is the case, please open a new issue.
